# default false
debug_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "Echo Web"
version = "0.0.1"

[server]
graceful = true
addr = ":8081"

# Domains
domain_api = "localhost"
domain_web = "localhost"
domain_socket = "localhost"

[database]
name = "echo"
user_name = "root"
db_name  = "test"
pwd  = "12345678"
host = "10.1.30.98"
port = "3306"

[redis]
server = "127.0.0.1:6379"
pwd = ""