# default false
debug_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "Echo Web"
version = "0.0.1"

[server]
graceful = true
addr = ":8080"

# Domains
domain_api = "localhost"
domain_web = "localhost"
domain_socket = "localhost"

[database]
name = "goweb_db"
user_name = "goweb_dba"
pwd  = "123456"
host = "127.0.0.1"
port = "3306"

[redis]
server = "127.0.0.1:6379"
pwd = "123456"